// packages/tinchi/src/components/Header.vue
<script lang="ts" setup>
import externalLinkIcon from '../assets/external-link-icon.svg';
</script>

<template>
    <header class="mt-12 mb-4 text-center">
        <h1 class="text-3xl">
            <a href="/" class="uppercase">KMA TINCHI</a>
        </h1>
        <p class="inline-flex gap-2 mt-2">
            <a href="https://www.facebook.com/kitclubKMA" target="_blank" rel="noreferrer" class="underline">
                KIT CLUB
                <img :src="externalLinkIcon" class="inline-block w-3 h-3 mb-4" alt="https://www.facebook.com/kitclubKMA" />
            </a>
            <!-- |
            <a href="https://github.com/ngosangns/tin-chi/issues" target="_blank" rel="noreferrer" class="underline">
                ISSUES
                <img :src="externalLinkIcon" class="inline-block w-3 h-3 mb-4" alt="https://www.facebook.com/kitclubKMA" />
            </a> -->
        </p>
    </header>
</template>

<style>
header {
    width: 100%;
    min-width: 60rem;
}
</style>

// packages/calendar/src/routes/Header.svelte
<script>
	import externalLinkIcon from '$lib/images/external-link-icon.svg';
</script>

<header class="mt-12 mb-4 text-center">
	<h1 class="text-3xl">
		<a href="/" class="uppercase">KIT Calendar</a>
	</h1>
	<p class="inline-flex gap-2 mt-2">
		<!-- <a href="/changelogs" class="underline">CHANGELOGS</a> |
		<a href="/about" class="underline">ABOUT</a> | -->
		<a
			href="https://www.facebook.com/kitclubKMA"
			target="_blank"
			rel="noreferrer"
			class="underline"
		>
			KIT CLUB
			<img
				src={externalLinkIcon}
				class="inline-block w-3 h-3 mb-4 invert"
				alt="https://www.facebook.com/kitclubKMA"
			/>
		</a>
		<!-- |
		<a
			href="https://github.com/ngosangns/kma-schedule-ngosangns/issues"
			class="underline"
			target="_blank"
			rel="noreferrer"
		>
			ISSUES
			<img
				src={externalLinkIcon}
				class="inline-block w-3 h-3 mb-4 invert"
				alt="https://github.com/ngosangns/kma-schedule-ngosangns/issues"
			/>
		</a> -->
	</p>
</header>

<style>
	header {
		width: 100%;
		min-width: 60rem;
	}
</style>
